require("user.impatient")

require("user.options")
require("user.plugins")
require("user.mappings")

require("user.autoDarkMode")
require("user.autopairs")
require("user.betterEscape")
require("user.bufferline")
require("user.clipImage")
require("user.colorizer")
require("user.colorscheme")
require("user.comments")
require("user.completions")
require("user.dress")
require("user.git")
require("user.lsp")
require("user.lualine")
require("user.telescope")
require("user.toggleterm")
require("user.tree")
require("user.treesitter")
require("user.vimtex")

require("nvim-surround").setup()
